### ISSUE TITLE
v2.12.14 is vulnerable to Cross Site Scripting (XSS)

### ISSUE THREAD

**Issue by katyalh** [wpcodefactory/eu-vat-for-woocommerce#2]
Hi WP factory team, 

I recently noticed this https://github.com/advisories/GHSA-q76r-wfxf-2r8x vulnerability in v2.12.14.

Any updates on this?

**Comment by BirendraMaharjan** [comment]
Hi @katyalh,

The vulnerability has already been fixed in v2.12.14. However, it seems that their database hasn’t been updated yet.

Here’s the patched link for your reference: https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/eu-vat-for-woocommerce/euuk-vat-manager-for-woocommerce-21212-reflected-cross-site-scripting

Thank you.

**Comment by katyalh** [comment]
Hi @BirendraMaharjan 

It seems like the same vulnerability is being reported for v2.12.14 https://patchstack.com/database/vulnerability/eu-vat-for-woocommerce/wordpress-eu-uk-vat-manager-for-woocommerce-plugin-2-12-8-cross-site-scripting-xss-vulnerability

any ideas why?

Thanks

**Comment by BirendraMaharjan** [comment]
Hi @katyalh,

We’ve released version 3.0.0, which fixes the vulnerability reported for version 2.12.14.

Thank you.
